import { useMemo, useState } from 'react'
import type { FormEvent, SyntheticEvent } from 'react'
import studySwapUniversityLogo from './assets/studyswap-university-logo.jpg'
import './App.css'

type Listing = { id: number; title: string; course: string; type: 'Sell' | 'Rent' | 'Swap' | 'Borrow' | 'Free'; price: string; imageUrl: string; owner: string; area: string; condition: string }

const listings: Listing[] = [
  { id: 1, title: 'Engineering Mechanics', course: 'CE 201 · 5th edition', type: 'Sell', price: '₱380', imageUrl: 'https://static.wixstatic.com/media/4a54d7_f8173b2b56174a91a249cf5b3432b31e~mv2.jpg/v1/fill/w_640%2Ch_624%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/4a54d7_f8173b2b56174a91a249cf5b3432b31e~mv2.jpg', owner: 'Miguel A.', area: 'North Campus', condition: 'Like new' },
  { id: 2, title: 'Casio fx-991ES Plus', course: 'Scientific calculator', type: 'Rent', price: '₱35 / week', imageUrl: 'https://i5.walmartimages.com/asr/05824bcf-2576-4720-9902-bce769ec4914.b8bc555632fce87bb1c12113c5213d88.jpeg', owner: 'Anne L.', area: 'Main Library', condition: 'Good condition' },
  { id: 3, title: 'Architecture drafting kit', course: 'Complete set · 12 pieces', type: 'Swap', price: 'Trade only', imageUrl: 'https://images.nexusapp.co/assets/bc/5a/ef/419658156.jpg', owner: 'Bea R.', area: 'South Gate', condition: 'Used once' },
  { id: 4, title: 'Organic Chemistry', course: 'CHEM 102 · 9th edition', type: 'Sell', price: '₱450', imageUrl: 'https://static.wixstatic.com/media/4a54d7_f8173b2b56174a91a249cf5b3432b31e~mv2.jpg/v1/fill/w_640%2Ch_624%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/4a54d7_f8173b2b56174a91a249cf5b3432b31e~mv2.jpg', owner: 'Jon C.', area: 'Engineering Building', condition: 'With notes' },
  { id: 5, title: 'Lab coat · Medium', course: 'White, button-up', type: 'Borrow', price: 'Free to borrow', imageUrl: 'https://www.coto.com.ar/vuelta-al-cole/images/guardapolvosss.jpg', owner: 'Tess M.', area: 'Science Hall', condition: 'Excellent' },
  { id: 6, title: 'Acrylic paint set', course: '24 colors + brushes', type: 'Free', price: 'Free', imageUrl: 'https://www.montmarte.com/cdn/shop/files/Mont-Marte-Acrylic-Paint-Set-Signature-12-pc-20-ml-0.67-US-fl-oz-MSCH1220_V01-Lifestyle1.jpg?v=1752129441', owner: 'Lex P.', area: 'Arts Wing', condition: 'Unused' },
]
const fallbackPhoto = 'https://static.wixstatic.com/media/4a54d7_f8173b2b56174a91a249cf5b3432b31e~mv2.jpg/v1/fill/w_640%2Ch_624%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/4a54d7_f8173b2b56174a91a249cf5b3432b31e~mv2.jpg'
const handleImageError = (event: SyntheticEvent<HTMLImageElement>) => { event.currentTarget.onerror = null; event.currentTarget.src = fallbackPhoto }
const initialConversations = [
  { id: 1, name: 'Miguel A.', initial: 'M', item: 'Engineering Mechanics', time: '10:24 AM', unread: true, messages: [{ from: 'Miguel A.', text: 'Hi Juan! The textbook is still available. Would North Campus work for you?', time: '10:24 AM' }] },
  { id: 2, name: 'Anne L.', initial: 'A', item: 'Casio fx-991ES Plus', time: 'Yesterday', unread: false, messages: [{ from: 'Anne L.', text: 'Sure, I can reserve the calculator for you until Friday.', time: 'Yesterday' }] },
  { id: 3, name: 'Bea R.', initial: 'B', item: 'Architecture drafting kit', time: 'Mon', unread: false, messages: [{ from: 'Bea R.', text: 'I am looking for a lab coat or a calculator to swap.', time: 'Mon' }] },
]

function Logo() { return <div className="brand"><img src={studySwapUniversityLogo} alt="StudySwap University" /></div> }

function App() {
  const [view, setView] = useState<'home' | 'browse' | 'post' | 'profile' | 'inbox'>('home')
  const [auth, setAuth] = useState<'signin' | 'signup' | null>(null)
  const [filter, setFilter] = useState('All')
  const [search, setSearch] = useState('')
  const [saved, setSaved] = useState<number[]>([1])
  const [selected, setSelected] = useState<Listing | null>(null)
  const [requestSent, setRequestSent] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [studentName, setStudentName] = useState<string | null>(null)
  const visibleListings = useMemo(() => listings.filter((item) => (filter === 'All' || item.type === filter) && (!search || `${item.title} ${item.course}`.toLowerCase().includes(search.toLowerCase()))), [filter, search])
  const toggleSaved = (id: number) => setSaved((items) => items.includes(id) ? items.filter((x) => x !== id) : [...items, id])
  const goToBrowse = (chosen = 'All') => { setFilter(chosen); setView('browse'); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <main className="app-shell">
    <header className="topbar"><button className="logo-button" onClick={() => setView('home')} aria-label="Go to home"><Logo /></button><nav className="desktop-nav"><button onClick={() => setView('home')} className={view === 'home' ? 'active' : ''}>Discover</button><button onClick={() => goToBrowse()} className={view === 'browse' ? 'active' : ''}>Browse</button><button onClick={() => setView('post')}>Post an item</button></nav><div className="account-actions">{studentName ? <button className="student-chip" onClick={() => setView('profile')}><span>J</span>{studentName}</button> : <><button className="text-button" onClick={() => setAuth('signin')}>Log in</button><button className="primary small" onClick={() => setAuth('signup')}>Join StudySwap</button></>}</div><button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">☰</button></header>
    {menuOpen && <div className="mobile-menu-panel"><button onClick={() => { setView('home'); setMenuOpen(false) }}>Discover</button><button onClick={() => { goToBrowse(); setMenuOpen(false) }}>Browse materials</button><button onClick={() => { setView('post'); setMenuOpen(false) }}>Post an item</button><button onClick={() => { setAuth('signin'); setMenuOpen(false) }}>Log in</button></div>}
    {view === 'home' && <Home onBrowse={goToBrowse} onPost={() => setView('post')} search={search} setSearch={setSearch} onSelect={setSelected} saved={saved} onSave={toggleSaved} />}
    {view === 'browse' && <Browse listings={visibleListings} filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} onSelect={setSelected} saved={saved} onSave={toggleSaved} />}
    {view === 'post' && <PostItem onAuth={() => setAuth('signup')} />}{view === 'profile' && <Profile studentName={studentName} onAuth={() => setAuth('signup')} onInbox={() => setView('inbox')} />}{view === 'inbox' && <Inbox studentName={studentName} onAuth={() => setAuth('signin')} />}
    <nav className="mobile-nav">{[['⌂','Home'],['⌕','Browse'],['＋','Post'],['◌','Inbox'],['☻','Profile']].map(([icon,label]) => <button key={label} className={(view === label.toLowerCase() || (label === 'Home' && view === 'home')) ? 'active' : ''} onClick={() => label === 'Post' ? setView('post') : label === 'Browse' ? goToBrowse() : label === 'Home' ? setView('home') : label === 'Inbox' ? setView('inbox') : setView('profile')}><span>{icon}</span>{label}</button>)}</nav>
    {auth && <AuthModal mode={auth} onClose={() => setAuth(null)} onSwitch={() => setAuth(auth === 'signin' ? 'signup' : 'signin')} onSuccess={(name) => { setStudentName(name); setAuth(null); setView('profile') }} />}{selected && <ItemModal item={selected} saved={saved.includes(selected.id)} onClose={() => { setSelected(null); setRequestSent(false) }} onSave={() => toggleSaved(selected.id)} requestSent={requestSent} setRequestSent={setRequestSent} />}
  </main>
}

type HomeProps = { onBrowse: (type?: string) => void; onPost: () => void; search: string; setSearch: (value: string) => void; onSelect: (item: Listing) => void; saved: number[]; onSave: (id: number) => void }
function Home({ onBrowse, onPost, search, setSearch, onSelect, saved, onSave }: HomeProps) { return <>
  <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span></span>Your campus marketplace</div><h1>Give your school<br /><em>stuff a second life.</em></h1><p>Buy, sell, swap, borrow, or rent academic materials with verified students on your campus.</p><div className="search-box"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && onBrowse()} placeholder="Search books, supplies, and more" /><button onClick={() => onBrowse()}>Search</button></div><div className="popular">Popular: <button onClick={() => { setSearch('calculator'); onBrowse() }}>Calculators</button><button onClick={() => { setSearch(''); onBrowse('Rent') }}>Rentals</button><button onClick={() => { setSearch(''); onBrowse('Swap') }}>Swaps</button></div></div><div className="hero-visual"><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="visual-tag tag-top">↗ Verified students</div><div className="visual-tag tag-bottom">♻ 240 items reused</div><div className="book-stack"><div className="book book-yellow">CHEM<br /><b>101</b></div><div className="book book-orange">design<br />basics</div><div className="book book-blue">CALCULUS<br /><b>II</b></div><div className="calculator">⌨</div><div className="pencil">✦</div></div></div></section>
  <section className="action-strip"><div><span className="icon-tile purple">◎</span><div><b>Find what you need</b><p>From textbooks to lab coats</p></div></div><div><span className="icon-tile yellow">↗</span><div><b>Give unused things a home</b><p>Earn, trade, or help a classmate</p></div></div><button className="outline-button" onClick={onPost}>Post an item <span>→</span></button></section>
  <section className="content-section"><div className="section-heading"><div><span className="section-kicker">EXPLORE BY PURPOSE</span><h2>What are you looking to do?</h2></div><button className="link-button" onClick={() => onBrowse()}>View all materials <span>→</span></button></div><div className="purpose-grid">{[['Buy','Find affordable materials','⌂','purple'],['Sell','Turn unused items into cash','↗','orange'],['Swap','Trade with fellow students','⇄','teal'],['Borrow','Use what you need, temporarily','⌁','blue'],['Rent','Get it for the semester','◷','yellow']].map(([title,sub,icon,style]) => <button className="purpose-card" key={title} onClick={() => onBrowse(title === 'Buy' ? 'Sell' : title)}><span className={`purpose-icon ${style}`}>{icon}</span><b>{title}</b><small>{sub}</small><span className="arrow">→</span></button>)}</div></section>
  <section className="content-section listings-section"><div className="section-heading"><div><span className="section-kicker">JUST ADDED</span><h2>Fresh from your campus</h2></div><button className="link-button" onClick={() => onBrowse()}>Browse all <span>→</span></button></div><ListingGrid items={listings.slice(0,4)} onSelect={onSelect} saved={saved} onSave={onSave} /></section>
  <section className="campus-banner"><div className="banner-art"><span>☼</span><span>✦</span><span>◒</span></div><div><span className="section-kicker">SAFE & SIMPLE</span><h2>Made for campus life.</h2><p>Connect with students using institutional emails, choose a familiar meet-up spot, and keep valuable materials in circulation.</p></div><div className="stats"><div><strong>2.4k</strong><span>students</span></div><div><strong>860</strong><span>materials shared</span></div></div></section>
</> }

type BrowseProps = { listings: Listing[]; filter: string; setFilter: (value: string) => void; search: string; setSearch: (value: string) => void; onSelect: (item: Listing) => void; saved: number[]; onSave: (id: number) => void }
function Browse({ listings: items, filter, setFilter, search, setSearch, onSelect, saved, onSave }: BrowseProps) { const types = ['All','Sell','Rent','Swap','Borrow','Free']; return <section className="browse-page"><div className="browse-intro"><span className="section-kicker">MARKETPLACE</span><h1>Find materials that<br /><em>fit your semester.</em></h1><div className="browse-search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search all materials" /></div></div><div className="filter-row"><button className="filter-button">☷ Filters</button>{types.map((type) => <button className={`filter-chip ${filter === type ? 'selected' : ''}`} key={type} onClick={() => setFilter(type)}>{type}</button>)}</div><div className="results-row"><span><b>{items.length}</b> materials available</span><button>Sort: <b>Most recent</b> ⌄</button></div><ListingGrid items={items} onSelect={onSelect} saved={saved} onSave={onSave} /></section> }

function ListingGrid({ items, onSelect, saved, onSave }: { items: Listing[]; onSelect: (item: Listing) => void; saved: number[]; onSave: (id: number) => void }) { return <div className="listing-grid">{items.map((item) => <article className="listing-card" key={item.id}><button className="listing-image" onClick={() => onSelect(item)}><span className={`type-badge ${item.type.toLowerCase()}`}>{item.type}</span><img className="item-photo" src={item.imageUrl} alt={item.title} onError={handleImageError} /><span className="item-scribble">✦</span></button><button className={`save-button ${saved.includes(item.id) ? 'saved' : ''}`} aria-label="Save item" onClick={() => onSave(item.id)}>{saved.includes(item.id) ? '♥' : '♡'}</button><div className="listing-info"><button className="item-title" onClick={() => onSelect(item)}>{item.title}</button><p>{item.course}</p><div className="item-meta"><b>{item.price}</b><span>{item.area}</span></div><div className="owner-line"><span className="avatar">{item.owner.charAt(0)}</span>{item.owner}<span className="verified">✓</span></div></div></article>)}</div> }

function PostItem({ onAuth }: { onAuth: () => void }) { return <section className="post-page"><div className="post-heading"><span className="section-kicker">SHARE WHAT YOU HAVE</span><h1>Pass it <em>forward.</em></h1><p>Make your unused materials useful to another student.</p></div><div className="post-card"><div className="post-progress"><span className="current">1</span><i></i><span>2</span><i></i><span>3</span></div><h2>What would you like to share?</h2><p>Choose a way to pass your material on.</p><div className="post-options">{['Sell','Rent','Swap','Give away'].map((option,index) => <button key={option} className={index === 0 ? 'chosen' : ''}><span>{['↗','◷','⇄','♡'][index]}</span><b>{option}</b><small>{['Set a fair price','Lend it for a period','Trade for something useful','Help someone out'][index]}</small></button>)}</div><button className="primary wide" onClick={onAuth}>Continue to sign up <span>→</span></button><p className="sign-in-note">Already have an account? <button onClick={onAuth}>Log in</button></p></div></section> }
function Profile({ studentName, onAuth, onInbox }: { studentName: string | null; onAuth: () => void; onInbox: () => void }) {
  if (!studentName) return <section className="profile-page"><div className="profile-card"><span className="profile-avatar">J</span><span className="section-kicker">YOUR STUDENT PROFILE</span><h1>Ready to make<br /><em>your first swap?</em></h1><p>Sign in to save materials, contact sellers, and manage your listings.</p><button className="primary wide" onClick={onAuth}>Create your account <span>→</span></button></div></section>
  return <section className="dashboard-page"><div className="dashboard-hero"><div><span className="section-kicker">YOUR STUDENT DASHBOARD</span><h1>Good afternoon, <em>Juan.</em></h1><p>Here’s what’s happening with your materials.</p></div><button className="primary" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>＋ Post an item</button></div><div className="dashboard-grid"><div className="dashboard-main"><div className="summary-grid"><article><span className="summary-icon violet">♡</span><div><b>4</b><p>Saved materials</p></div></article><article><span className="summary-icon amber">◷</span><div><b>2</b><p>Active requests</p></div></article><article><span className="summary-icon mint">✓</span><div><b>3</b><p>Completed swaps</p></div></article></div><section className="dashboard-section"><div className="dashboard-heading"><div><span className="section-kicker">ACTIVE REQUESTS</span><h2>Keep things moving</h2></div><button onClick={onInbox}>View inbox →</button></div><div className="request-card"><div className="request-photo">📘</div><div><span className="request-status">Waiting for response</span><b>Engineering Mechanics</b><p>Request sent to Miguel A. · North Campus</p></div><button className="outline-button" onClick={onInbox}>Message Miguel</button></div><div className="request-card"><div className="request-photo lilac">🧮</div><div><span className="request-status confirmed">Reserved until Friday</span><b>Casio fx-991ES Plus</b><p>Rental request accepted by Anne L.</p></div><button className="outline-button" onClick={onInbox}>View chat</button></div></section></div><aside className="dashboard-side"><div className="account-card"><span className="profile-avatar">J</span><div><b>{studentName}</b><p><span className="verified">✓</span> CIT verified student</p></div><button>•••</button></div><div className="dashboard-section compact"><span className="section-kicker">YOUR IMPACT</span><h2>Small choices, real change.</h2><div className="impact-ring"><strong>8</strong><span>materials<br />kept in use</span></div><p className="impact-copy">You’ve helped save an estimated ₱1,250 this school year.</p></div><button className="inbox-callout" onClick={onInbox}><span>◌</span><div><b>2 conversations need you</b><p>See new messages in Inbox</p></div><i>→</i></button></aside></div></section>
}

function Inbox({ studentName, onAuth }: { studentName: string | null; onAuth: () => void }) {
  const [conversations, setConversations] = useState(initialConversations)
  const [activeId, setActiveId] = useState(1)
  const [draft, setDraft] = useState('')
  if (!studentName) return <section className="profile-page"><div className="profile-card"><span className="profile-avatar">✦</span><span className="section-kicker">STAY IN THE LOOP</span><h1>Your campus<br /><em>inbox awaits.</em></h1><p>Sign in to safely message verified students about materials and exchanges.</p><button className="primary wide" onClick={onAuth}>Log in to Inbox <span>→</span></button></div></section>
  const active = conversations.find((conversation) => conversation.id === activeId) ?? conversations[0]
  const selectConversation = (id: number) => { setConversations((items) => items.map((item) => item.id === id ? { ...item, unread: false } : item)); setActiveId(id) }
  const sendMessage = (event: FormEvent) => { event.preventDefault(); const cleanDraft = draft.trim(); if (!cleanDraft) return; setConversations((items) => items.map((item) => item.id === active.id ? { ...item, time: 'Now', messages: [...item.messages, { from: 'You', text: cleanDraft, time: 'Now' }] } : item)); setDraft('') }
  return <section className="inbox-page"><div className="inbox-heading"><div><span className="section-kicker">MESSAGES</span><h1>Inbox</h1></div><button className="compose-button">＋ New message</button></div><div className="inbox-shell"><aside className="conversation-list"><div className="inbox-search">⌕ <input placeholder="Search messages" /></div>{conversations.map((conversation) => <button className={`conversation ${conversation.id === active.id ? 'selected' : ''}`} key={conversation.id} onClick={() => selectConversation(conversation.id)}><span className="conversation-avatar">{conversation.initial}</span><div><div className="conversation-top"><b>{conversation.name}</b><time>{conversation.time}</time></div><span className="conversation-item">{conversation.item}</span><p>{conversation.messages.at(-1)?.text}</p></div>{conversation.unread && <i></i>}</button>)}</aside><main className="message-panel"><header><div><span className="conversation-avatar">{active.initial}</span><div><b>{active.name} <span className="verified">✓</span></b><p>Verified student · Usually replies in an hour</p></div></div><button>•••</button></header><div className="item-context"><span>📘</span><div><b>{active.item}</b><p>{active.id === 1 ? 'Buy · ₱380' : active.id === 2 ? 'Rent · ₱35 / week' : 'Swap · Trade only'}</p></div><button>View item →</button></div><div className="message-thread"><span className="message-day">Today</span>{active.messages.map((message, index) => <div key={`${message.time}-${index}`} className={`message-bubble ${message.from === 'You' ? 'mine' : ''}`}><p>{message.text}</p><time>{message.time}</time></div>)}</div><form className="message-composer" onSubmit={sendMessage}><button type="button">＋</button><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder={`Message ${active.name}`} /><button className="send-button" type="submit">Send ↑</button></form></main></div></section>
}

function AuthModal({ mode, onClose, onSwitch, onSuccess }: { mode: 'signin' | 'signup'; onClose: () => void; onSwitch: () => void; onSuccess: (name: string) => void }) { const [showPassword,setShowPassword] = useState(false); const submit = (event: FormEvent) => { event.preventDefault(); onSuccess(signUp ? 'Juan Dela Cruz' : 'Juan Dela Cruz') }; const signUp = mode === 'signup'; return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="auth-modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose}>×</button><Logo /><div className="auth-copy"><span className="section-kicker">{signUp ? 'JOIN YOUR CAMPUS COMMUNITY' : 'WELCOME BACK'}</span><h2>{signUp ? <>A smarter way to<br /><em>share resources.</em></> : <>Good to see you<br /><em>again.</em></>}</h2><p>{signUp ? 'Create your verified student account in just a few steps.' : 'Sign in to pick up where you left off.'}</p></div><form onSubmit={submit}>{signUp && <><label>Full name<input required placeholder="Juan Dela Cruz" /></label><label>School or institution<select defaultValue=""><option value="" disabled>Select your school</option><option>Cebu Institute of Technology</option><option>Other institution</option></select></label></>}<label>Institutional email<div className="input-with-icon"><input type="email" required placeholder="juan.delacruz@cit.edu" /><span>@</span></div></label>{signUp && <label>Campus address / meet-up area<input required placeholder="e.g. CIT Main Campus, North Gate" /></label>}<label>Password<div className="input-with-icon"><input type={showPassword ? 'text' : 'password'} required minLength={8} placeholder="At least 8 characters" /><button type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? 'Hide' : 'Show'}</button></div></label>{signUp && <label>Confirm password<input type="password" required minLength={8} placeholder="Repeat your password" /></label>}{signUp && <label className="checkbox-label"><input type="checkbox" required /><span>I agree to the <button type="button">Terms</button> and Community Guidelines.</span></label>}<button className="primary wide" type="submit">{signUp ? 'Create account' : 'Log in'} <span>→</span></button></form>{!signUp && <><div className="demo-credentials"><span>DEMO ACCOUNT</span><p><b>juan.delacruz@cit.edu</b><b>StudySwap2026</b></p></div><button className="demo-button" onClick={() => onSuccess('Juan Dela Cruz')}>Use demo account <span>→</span></button></>}<p className="auth-switch">{signUp ? 'Already have an account?' : 'New to StudySwap?'} <button onClick={onSwitch}>{signUp ? 'Log in' : 'Create an account'}</button></p>{signUp && <div className="verification-note"><span>✓</span><p>We’ll send a verification link to your institutional email. Your address is never shown publicly.</p></div>}</div></div> }

function ItemModal({ item, saved, onClose, onSave, requestSent, setRequestSent }: { item: Listing; saved: boolean; onClose: () => void; onSave: () => void; requestSent: boolean; setRequestSent: (value: boolean) => void }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="item-modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose}>×</button><div className="detail-image"><span className={`type-badge ${item.type.toLowerCase()}`}>{item.type}</span><img src={item.imageUrl} alt={item.title} onError={handleImageError} /></div><div className="detail-content"><div className="detail-top"><div><span className="section-kicker">{item.course}</span><h2>{item.title}</h2></div><button className={`save-button inline-save ${saved ? 'saved' : ''}`} onClick={onSave}>{saved ? '♥' : '♡'}</button></div><div className="detail-price">{item.price}</div><p className="detail-description">In {item.condition.toLowerCase()} condition. A well-loved material looking for its next semester.</p><div className="seller-box"><span className="avatar large">{item.owner.charAt(0)}</span><div><b>{item.owner} <span className="verified">✓</span></b><p>Verified student · {item.area}</p></div><button>View profile</button></div>{requestSent ? <div className="request-success"><span>✓</span><div><b>Request sent!</b><p>{item.owner} will be notified and can respond in Inbox.</p></div></div> : <button className="primary wide" onClick={() => setRequestSent(true)}>{item.type === 'Sell' ? 'Message seller' : `Request to ${item.type.toLowerCase()}`} <span>→</span></button>}<p className="privacy-note">⌖ Meet up safely on campus. Your personal address stays private.</p></div></div></div> }
export default App
